include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - lib/*.g.dart
    - lib/**/*.g.dart
    - lib/**/**/*.g.dart
    - lib/**/**/**/*.g.dart
    - /*.g.dart

linter:
  rules:
    # It's disabled because performance improvement is insignificant
    prefer_const_constructors: false
