name: wspieramprzyrode
description: WspieramPrzyrode Mobile App

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # ui
  cupertino_icons: ^0.1.3
  font_awesome_flutter: ^8.8.1
  theme_provider: ^0.3.3
  image_picker: ^0.6.7 # only mobile

  # architecture, di and tools
  responsive_builder: ^0.2.0+2
  get_it: ^4.0.2
  provider: ^4.1.2
  app_settings: ^4.0.0 # only mobile
  permission_handler: ^5.0.0+hotfix.8 # only mobile
  lint: ^1.2.0
  flutter_bloc: ^6.0.1
  bloc: ^6.0.1
  js: ^0.6.0 # mapping js interfaces to dart
  intl: ^0.16.1

  # maps and location
  flutter_map: "0.10.1+1" # only mobile
  flutter_map_marker_cluster: any
  location: "3.0.2"

  # storage
  hive: ^1.4.1+1

  # networking
  retrofit: ^1.3.4
  dio: ^3.0.9
  pretty_dio_logger: ^1.1.1
  json_annotation: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any

  retrofit_generator: ^1.3.7
  build_runner: ^1.10.0
  json_serializable: ^3.3.0

flutter:
  uses-material-design: true
  generate: true
