name: Lint And Test Code Base

on:
  pull_request:
    branches: [master]

env:
  flutter_version: "1.20.0"
  flutter_channel: "beta"
  java_version: "12.x"

jobs:
  lint-and-test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.java_version }}
      - name: Install Flutter channel ${{ env.flutter_channel }}
        uses: subosito/flutter-action@v1
        with:
          channel: ${{ env.flutter_channel }}
      - name: Enable web support
        run: flutter config --enable-web
      - name: Install packages
        run: flutter pub get
      - name: Flutter analyze
        run: flutter analyze
      - name: Unit test
        run: flutter test
